[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid
user=root

[program:sshd]
command=/usr/sbin/sshd -D
user=root
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=root
autorestart=true
